<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [
	{
        "backMenu":[
			{
			    "child":[
			        {
			            "buttons":[
			                "查看",
                            "新增",
                            "修改",
                            "删除"
			            ],
			            "menu":"员工管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"员工管理"
			}
			,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"资产管理",
                        "menuJump":"列表",
                        "tableName":"zichan"
                    }
                ],
                "menu":"资产管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"资产报废管理",
                        "menuJump":"列表",
                        "tableName":"baofei"
                    }
                ],
                "menu":"资产报废管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"部门管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBumen"
                    }
                ],
                "menu":"部门管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
                            "新增",
                            "修改",
                            "删除"
			            ],
			            "menu":"资产分类管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryZichan"
			        }
			    ],
			    "menu":"资产分类管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"资产维修管理",
                        "menuJump":"列表",
                        "tableName":"weixiu"
                    }
                ],
                "menu":"资产维修管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"资产折旧管理",
                        "menuJump":"列表",
                        "tableName":"zhejiu"
                    }
                ],
                "menu":"资产折旧管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
			{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"资产管理",
	                    "menuJump":"列表",
	                    "tableName":"zichan"
	                }
	            ],
	            "menu":"资产管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"资产报废管理",
	                    "menuJump":"列表",
	                    "tableName":"baofei"
	                }
	            ],
	            "menu":"资产报废管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"部门管理",
	                    "menuJump":"列表",
	                    "tableName":"dictionaryBumen"
	                }
	            ],
	            "menu":"部门管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"资产分类管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryZichan"
			        }
			    ],
			    "menu":"资产分类管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"资产维修管理",
	                    "menuJump":"列表",
	                    "tableName":"weixiu"
	                }
	            ],
	            "menu":"资产维修管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"资产折旧管理",
	                    "menuJump":"列表",
	                    "tableName":"zhejiu"
	                }
	            ],
	            "menu":"资产折旧管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"员工",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
